import Omsorgsdager from "./types/Omsorgsdager";
import Barn from "./types/Barn";
import Omsorgsprinsipper from "./types/Omsorgsprinsipper";
import Forelder from "./types/Forelder";
import Overføringsdager from "./types/Overføringsdager";
export declare const GRUNNRETTSDAGER_1_2_BARN: number;
export declare const GRUNNRETTSDAGER_3_ELLER_FLER_BARN: number;
export declare const KRONISK_SYKT_BARN_DAGER: number;
export declare const ALENEOMSORG_KRONISK_SYKT_BARN_DAGER: number;
export declare const ALENEOMSORGDAGER_1_2_BARN: number;
export declare const ALENEOMSORGDAGER_3_ELLER_FLERE_BARN: number;
export declare const erPositivtHeltall: (value: number) => boolean;
export declare const grunnrettsdager: (barn: Barn[], inkluderKoronadager: boolean) => Omsorgsdager;
export declare const kroniskSyktDager: (barn: Barn[], inkluderKoronadager: boolean) => Omsorgsdager;
export declare const aleneomsorgKroniskSykeDager: (barn: Barn[], inkluderKoronadager: boolean) => Omsorgsdager;
export declare const aleneomsorgsdager: (barn: Barn[], inkluderKoronadager: boolean) => Omsorgsdager;
export declare const effektiveOverføringsdager: ({ overførteKoronadager, mottatteKoronadager, fordelteNormaldager, mottatteNormaldager, }: Overføringsdager, grunnrettsdager: number, inkluderKoronadager: boolean) => Omsorgsdager;
export declare const sumOverføringsdager: (foreldre: Forelder[], inkluderKoronadager: boolean) => Overføringsdager;
export declare const beregnOmsorgsdager: (barn: Barn[] | undefined, inkluderKoronadager: boolean) => Omsorgsprinsipper;
